query ($page: Int!)  {
  episodes (page: $page){
   	info {
      count,
      pages
    },
  	results {
      id,
      name,
      air_date,
      episode,
      characters {
        id,
      }
    }
  }
}