query ($page: Int!) {
  characters  (page: $page){
    info {
      count,
      pages
    },
    results {
      id,
      name
      status,
      species,
      gender,
      image,
      origin {
        name,
      },
    }
  }
}