# Write your query or mutation here
query {
  characters {
    info {
      count,
      pages
    },
    results {
      id,
      name
      status,
      species,
      gender,
      image,
      origin {
        name,
      },
    }
  }
}